# Unique name for this workflow
name: Pull Request Workflow Docker

# Definition when the workflow should run
on:
    workflow_dispatch:
    pull_request:
         types: [opened, edited, synchronize, reopened]

# Jobs to be executed
jobs:
    # Dummy job used to skip CI run on automated PRs  my-job:
      my-job:
        runs-on: ubuntu-latest
        environment: develop 
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - name: Run the build process with Docker
              uses: addnab/docker-run-action@v3
              with:
                  image: nishantwavhal/nishantcli:0.0.2
                  run: |
                    node bin/nishant-cli.js gen-sfdx --commandtype file --commandname getComponentFileMap
                    node bin/nishant-cli.js gen-sfdx --commandtype file --commandname getFilesNames
                    sf --version

                    
          
               
                       
            
