# Unique name for this workflow
name: Hello World

# Definition when the workflow should run
on:
    workflow_dispatch:
        inputs:
            prerelease:
                description: 'Run on a prerelease org?'
                required: false
                type: boolean
    pull_request:
         types: [opened, edited, synchronize, reopened]

# Jobs to be executed
jobs:
    # Dummy job used to skip CI run on automated PRs  my-job:
      my-job:
        runs-on: ubuntu-latest
        steps: 
            - name: Noop
              run: |
                  echo "Skipping CI run for automated PRs."
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - name: Get changed files
              id: changed-files
              run: |
                echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            
            - name: List changed files
              run: |
                 for file in ${{ steps.changed-files.outputs.changed_files }}
                    do
                        if [[ $file = *test || $file = *Test ]]
                            then 
                                fileSet=["basename${file}"];
                                echo "$file was changed";
                        fi
                    done
                    echo "$fileSet"
                    
                 declare -a fileSet    
                 for file in ${{ steps.changed-files.outputs.changed_files }}
                    do
                                fileSet=["basename${file}"];
                                echo "$file was changed";
                        
                    done
                 echo "$fileSet"
                    
            - name : 'Install Salesforce CLI'
              run: |
                  npm install @salesforce/cli --location=global
                  nodeInstallPath=$(npm config get prefix)
                  echo "$nodeInstallPath/bin" >> $GITHUB_PATH
                  sf --version
            
            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
              shell: bash
              run: |
                  echo ${{ secrets.SFDX_SECRET}}
                    
           
